version: '3.8'  

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    volumes:
      - ./nats.conf/nats-server.conf:/etc/nats-server.conf      
    restart: always



  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086" 
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

  daemon:
    build:
      context: ./deamonService
      dockerfile: Dockerfile
    environment:
      - NATSUSER=daemon_service
      - NATSPASSWORD=secure_daemon_password
      - NATSHOST=nats
      - NATSPORT=4222
    depends_on:
      - nats

  writer:
    build:
      context: ./writerService
      dockerfile: Dockerfile
    environment:
      - NATSUSER=writer_service
      - NATSPASSWORD=secure_writer_password
      - NATSHOST=nats
      - NATSPORT=4222
      - INFLUXURL=http://influxdb:8086
      - INFLUXTOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
    depends_on:
      - nats
      - influxdb
      - daemon
    restart: always

  reader:
    build:
      context: ./readerService
      dockerfile: Dockerfile
    environment:
      - NATSUSER=reader_service
      - NATSPASSWORD=secure_reader_password
      - NATSHOST=nats
      - NATSPORT=4222
      - INFLUXURL=http://influxdb:8086
      - INFLUXTOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
    depends_on:
      - nats
      - influxdb
      - writer
    restart: always

  client:
    build:
      context: ./clientService
      dockerfile: Dockerfile
    environment:
      - NATSUSER=client_service
      - NATSPASSWORD=secure_client_password
      - NATSHOST=nats
      - NATSPORT=4222
      - INFLUXURL=http://influxdb:8086
      - INFLUXTOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
    depends_on:
      - nats
      - influxdb
      - reader
    restart: always
